module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)

changes to this file should not be tracked:
`$ git update-index --skip-worktree tests/DocumentationCodeSnippetTest.elm`

-}

import Expect
import Test exposing (Test, test)


tests : Test
tests =
    test "placeholder" <| always (Expect.equal True True)
